In [3]:
import pandas as pd

df = pd.read_excel('movies-db.xlsx', sheet_name='financials')
df

    movie_id    budget   revenue       unit currency
0        101      1.00      12.5   Billions      INR
1        102    200.00     954.8   Millions      USD
2        103    165.00     644.8   Millions      USD
3        104    180.00     854.0   Millions      USD
4        105    250.00     670.0   Millions      USD
5        107    400.00    2000.0   Millions      INR
6        108    550.00    4000.0   Millions      INR
7        109    390.00    1360.0   Millions      INR
8        110      1.40       3.5   Billions      INR
9        111     25.00      73.3   Millions      USD
10       113    165.00     701.8   Millions      USD
11       114    205.00     365.3   Millions      USD
12       115     55.00     307.1   Millions      USD
13       116    103.00     460.5   Millions      USD
14       117    200.00    2202.0   Millions      USD
15       118      3.18       3.3   Millions      USD
16       119    237.00    2847.0   Millions      USD
17       120      7.20     291.0   Millions      USD
18       121    185.00    1006.0   Millions      USD
19       122     22.00     322.2   Millions      USD
20       123     63.00    1046.0   Millions      USD
21       124     15.50     263.1   Millions      USD
22       125    400.00    2798.0   Millions      USD
23       126    400.00    2048.0   Millions      USD
24       127  70000.00  100000.0  Thousands      INR
25       128    120.00    1350.0   Millions      INR
26       129    100.00     410.0   Millions      INR
27       130    850.00    8540.0   Millions      INR
28       131      1.00       5.9   Billions      INR
29       132      2.00       3.6   Billions      INR
30       133      5.50      12.0   Billions      INR
31       134      1.80       6.5   Billions      INR
32       135    250.00    3409.0   Millions      INR
33       136    900.00   11690.0   Millions      INR
34       137    216.70     370.6   Millions      USD
35       138    177.00     714.4   Millions      USD
36       139      1.80       3.1   Billions      INR
37       140    500.00     950.0   Millions      INR
38       406     30.00     350.0   Millions      INR
39       412    160.00     836.8   Millions      USD

In [4]:
# Convert revenue to millions based on unit
def convert_to_millions(row):
    if row['unit'] == 'Billions':
        return row['revenue'] * 1000
    elif row['unit'] == 'Thousands':
        return row['revenue'] / 1000
    else:
        return row['revenue']

df['revenue_mils'] = df.apply(convert_to_millions, axis=1)
df

    movie_id    budget   revenue       unit currency  revenue_mils
0        101      1.00      12.5   Billions      INR       12500.0
1        102    200.00     954.8   Millions      USD         954.8
2        103    165.00     644.8   Millions      USD         644.8
3        104    180.00     854.0   Millions      USD         854.0
4        105    250.00     670.0   Millions      USD         670.0
5        107    400.00    2000.0   Millions      INR        2000.0
6        108    550.00    4000.0   Millions      INR        4000.0
7        109    390.00    1360.0   Millions      INR        1360.0
8        110      1.40       3.5   Billions      INR        3500.0
9        111     25.00      73.3   Millions      USD          73.3
10       113    165.00     701.8   Millions      USD         701.8
11       114    205.00     365.3   Millions      USD         365.3
12       115     55.00     307.1   Millions      USD         307.1
13       116    103.00     460.5   Millions      USD         460.5
14       117    200.00    2202.0   Millions      USD        2202.0
15       118      3.18       3.3   Millions      USD           3.3
16       119    237.00    2847.0   Millions      USD        2847.0
17       120      7.20     291.0   Millions      USD         291.0
18       121    185.00    1006.0   Millions      USD        1006.0
19       122     22.00     322.2   Millions      USD         322.2
20       123     63.00    1046.0   Millions      USD        1046.0
21       124     15.50     263.1   Millions      USD         263.1
22       125    400.00    2798.0   Millions      USD        2798.0
23       126    400.00    2048.0   Millions      USD        2048.0
24       127  70000.00  100000.0  Thousands      INR         100.0
25       128    120.00    1350.0   Millions      INR        1350.0
26       129    100.00     410.0   Millions      INR         410.0
27       130    850.00    8540.0   Millions      INR        8540.0
28       131      1.00       5.9   Billions      INR        5900.0
29       132      2.00       3.6   Billions      INR        3600.0
30       133      5.50      12.0   Billions      INR       12000.0
31       134      1.80       6.5   Billions      INR        6500.0
32       135    250.00    3409.0   Millions      INR        3409.0
33       136    900.00   11690.0   Millions      INR       11690.0
34       137    216.70     370.6   Millions      USD         370.6
35       138    177.00     714.4   Millions      USD         714.4
36       139      1.80       3.1   Billions      INR        3100.0
37       140    500.00     950.0   Millions      INR         950.0
38       406     30.00     350.0   Millions      INR         350.0
39       412    160.00     836.8   Millions      USD         836.8

In [5]:
# Convert revenue to INR
def convert_to_inr(row):
    if row['currency'] == 'USD':
        return row['revenue_mils'] * 83.95
    else:
        return row['revenue_mils']

df['revenue_inr_mils'] = df.apply(convert_to_inr, axis=1)
df

,movie_id,budget,revenue,unit,currency,revenue_mils,revenue_inr_mils
0,101,1.00,12.5,Billions,INR,12500.0,12500.000
1,102,200.00,954.8,Millions,USD,954.8,80155.460
2,103,165.00,644.8,Millions,USD,644.8,54130.960
3,104,180.00,854.0,Millions,USD,854.0,71693.300
4,105,250.00,670.0,Millions,USD,670.0,56246.500
5,107,400.00,2000.0,Millions,INR,2000.0,2000.000
6,108,550.00,4000.0,Millions,INR,4000.0,4000.000
7,109,390.00,1360.0,Millions,INR,1360.0,1360.000
8,110,1.40,3.5,Billions,INR,3500.0,3500.000
9,111,25.00,73.3,Millions,USD,73.3,6153.535
10,113,165.00,701.8,Millions,USD,701.8,58916.110
11,114,205.00,365.3,Millions,USD,365.3,30666.935
12,115,55.00,307.1,Millions,USD,307.1,25781.045
13,116,103.00,460.5,Millions,USD,460.5,38658.975
14,117,200.00,2202.0,Millions,USD,2202.0,184857.900
15,118,3.18,3.3,Millions,USD,3.3,277.035
16,119,237.00,2847.0,Millions,USD,2847.0,239005.650
17,120,7.20,291.0,Millions,USD,291.0,24429.450
18,121,185.00,1006.0,Millions,USD,1006.0,84453.700
19,122,22.00,322.2,Millions,USD,322.2,27048.690
20,123,63.00,1046.0,Millions,USD,1046.0,87811.700
21,124,15.50,263.1,Millions,USD,263.1,22087.245
22,125,400.00,2798.0,Millions,USD,2798.0,234892.100
23,126,400.00,2048.0,Millions,USD,2048.0,171929.600
24,127,70000.00,100000.0,Thousands,INR,100.0,100.000
25,128,120.00,1350.0,Millions,INR,1350.0,1350.000
26,129,100.00,410.0,Millions,INR,410.0,410.000
27,130,850.00,8540.0,Millions,INR,8540.0,8540.000
28,131,1.00,5.9,Billions,INR,5900.0,5900.000
29,132,2.00,3.6,Billions,INR,3600.0,3600.000
30,133,5.50,12.0,Billions,INR,12000.0,12000.000
31,134,1.80,6.5,Billions,INR,6500.0,6500.000
32,135,250.00,3409.0,Millions,INR,3409.0,3409.000
33,136,900.00,11690.0,Millions,INR,11690.0,11690.000
34,137,216.70,370.6,Millions,USD,370.6,31111.870
35,138,177.00,714.4,Millions,USD,714.4,59973.880
36,139,1.80,3.1,Billions,INR,3100.0,3100.000
37,140,500.00,950.0,Millions,INR,950.0,950.000
38,406,30.00,350.0,Millions,INR,350.0,350.000
39,412,160.00,836.8,Millions,USD,836.8,70249.360

In [6]:
# Calculate profit in INR in millions
df['profit_inr_mils'] = df['revenue_inr_mils'] - df['budget']
df

,movie_id,budget,revenue,unit,currency,revenue_mils,revenue_inr_mils,profit_inr_mils
0,101,1.00,12.5,Billions,INR,12500.0,12500.000,12499.000
1,102,200.00,954.8,Millions,USD,954.8,80155.460,79955.460
2,103,165.00,644.8,Millions,USD,644.8,54130.960,53965.960
3,104,180.00,854.0,Millions,USD,854.0,71693.300,71513.300
4,105,250.00,670.0,Millions,USD,670.0,56246.500,55996.500
5,107,400.00,2000.0,Millions,INR,2000.0,2000.000,1600.000
6,108,550.00,4000.0,Millions,INR,4000.0,4000.000,3450.000
7,109,390.00,1360.0,Millions,INR,1360.0,1360.000,970.000
8,110,1.40,3.5,Billions,INR,3500.0,3500.000,3498.600
9,111,25.00,73.3,Millions,USD,73.3,6153.535,6128.535
10,113,165.00,701.8,Millions,USD,701.8,58916.110,58751.110
11,114,205.00,365.3,Millions,USD,365.3,30666.935,30461.935
12,115,55.00,307.1,Millions,USD,307.1,25781.045,25726.045
13,116,103.00,460.5,Millions,USD,460.5,38658.975,38555.975
14,117,200.00,2202.0,Millions,USD,2202.0,184857.900,184657.900
15,118,3.18,3.3,Millions,USD,3.3,277.035,273.855
16,119,237.00,2847.0,Millions,USD,2847.0,239005.650,238768.650
17,120,7.20,291.0,Millions,USD,291.0,24429.450,24422.250
18,121,185.00,1006.0,Millions,USD,1006.0,84453.700,84268.700
19,122,22.00,322.2,Millions,USD,322.2,27048.690,27026.690
20,123,63.00,1046.0,Millions,USD,1046.0,87811.700,87748.700
21,124,15.50,263.1,Millions,USD,263.1,22087.245,22071.745
22,125,400.00,2798.0,Millions,USD,2798.0,234892.100,234492.100
23,126,400.00,2048.0,Millions,USD,2048.0,171929.600,171529.600
24,127,70000.00,100000.0,Thousands,INR,100.0,100.000,-69900.000
25,128,120.00,1350.0,Millions,INR,1350.0,1350.000,1230.000
26,129,100.00,410.0,Millions,INR,410.0,410.000,310.000
27,130,850.00,8540.0,Millions,INR,8540.0,8540.000,7690.000
28,131,1.00,5.9,Billions,INR,5900.0,5900.000,5899.000
29,132,2.00,3.6,Billions,INR,3600.0,3600.000,3598.000
30,133,5.50,12.0,Billions,INR,12000.0,12000.000,11994.500
31,134,1.80,6.5,Billions,INR,6500.0,6500.000,6498.200
32,135,250.00,3409.0,Millions,INR,3409.0,3409.000,3159.000
33,136,900.00,11690.0,Millions,INR,11690.0,11690.000,10790.000
34,137,216.70,370.6,Millions,USD,370.6,31111.870,30895.170
35,138,177.00,714.4,Millions,USD,714.4,59973.880,59796.880
36,139,1.80,3.1,Billions,INR,3100.0,3100.000,3098.200
37,140,500.00,950.0,Millions,INR,950.0,950.000,450.000
38,406,30.00,350.0,Millions,INR,350.0,350.000,320.000
39,412,160.00,836.8,Millions,USD,836.8,70249.360,70089.360